name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

      # Install all SDK versions targeted in DomainResults.MVC project
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack DomainResult (Common)
      run: dotnet pack ./src/Common/DomainResults.Common.csproj --output nuget-packages --configuration Release
    - name: Pack DomainResult (full)
      run: dotnet pack ./src/Mvc/DomainResults.Mvc.csproj --output nuget-packages --configuration Release
    - name: NuGet publish
      run: find nuget-packages -name '*.nupkg' | xargs -i dotnet nuget push {} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: nuget-packages/**/*