name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Pack DomainResult (Common)
      run: dotnet pack ./src/Common/DomainResults.Common.csproj --output nuget-packages --configuration Release
    - name: Pack DomainResult (full)
      run: dotnet pack ./src/Mvc/DomainResults.Mvc.csproj --output nuget-packages --configuration Release
    - name: NuGet publish
      run: find nuget-packages -name '*.nupkg' | xargs -i dotnet nuget push {} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: nuget-packages/**/*